# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
	config.vm.define "win" do |win|
		win.vm.box = "opentable/win-2012r2-standard-amd64-nocm"
		win.vm.hostname = 'windows-server'
		win.vm.network :private_network, ip: "192.168.2.11"		
		win.vm.provider :virtualbox do |v|
			v.customize ["modifyvm", :id, "--memory", 1024]
			v.customize ["modifyvm", :id, "--name","windows-server"]
  		end
	end
end
